/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khosy.quiz.gui;

import com.khosy.quiz.lib.ComboModel;
import com.khosy.quiz.lib.Item;
import com.khosy.quiz.lib.TabelModel;
import com.khosy.quiz.lib.Transaksi;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.applet.Main;

/**
 *
 * @author khosy
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    private int id = 0; // variabel id untuk membuat id kode
    private String kode; // variabel kode untuk menyimpan kode
    private ComboModel comboModel; // untuk membuat Jcombo box model
    private DefaultTableModel tabelModel; // untuk membuat Jtable model
    private ArrayList<Item> barang = new ArrayList<>(); //variabel barang untuk menyimpan barang
    
    public Form() {
        this.comboModel = new ComboModel(); // untuk menginstansi model dari Jcombo box
            this.comboModel.tambahItem(new Item("Kopi", new Float(50000))); 
            this.comboModel.tambahItem(new Item("Gula", new Float(20000)));  
            this.comboModel.tambahItem(new Item("Susu", new Float(30000)));  
        
            //untuk membuat kolom nama
        TabelModel tabelModel = new TabelModel();
        this.tabelModel = new DefaultTableModel(tabelModel.getKolom(), 0);
        
        initComponents();
    }
    
    // untuk menambahkan id dengan penambahan 1
    private void tambahId() {
        this.id += 1;
    }
    
    // untuk mengurangi id dengan pengurangan 1
    private void kurangId() {
        this.id -= 1;
    }
    
    
     private String setKode() {
        this.tambahId();
        String tglWkt = new SimpleDateFormat("yyMMdd").format(new Date()); // get Current date as String;
        this.kode = String.format(tglWkt+"%02d", this.id);  // then merge it with id with 0 pad
        return kode;
    }
     
     private Object[] addItem(String nama, int jumlah) {
        float harga = 0;
        Item[] items = this.comboModel.toArray();
        for(int i = 0; i < items.length; i++) {
            if(nama.equalsIgnoreCase(items[i].getNama())) {
                harga = items[i].getHarga();
            }
        } 
        Object[] o = {
          nama,
          harga,
          jumlah
        };
        return o;
    }
     
     // menambahkan fungsi update jumlah item
    private void updateJumlah(String nama, int tambah) {
        ArrayList<String> item = new ArrayList<>();
        for (int i = 0; i < tabelModel.getRowCount(); i++){
            item.add(tabelModel.getValueAt(i, 0).toString());
        }
        for(int i = 0; i < item.size(); i++) {
            if(item.get(i).equals(nama)) {
                int jumlah = new Integer(tabelModel.getValueAt(i, 2).toString());
                tabelModel.setValueAt(jumlah+tambah, i, 2);  
            } 
        }
    } 
     
     // fungsi untuk mengecek apakah ada item yang terduplikasi
    private boolean isDuplicate(String nama) {
        boolean hasil = false;
        ArrayList<String> item = new ArrayList<>();
        for (int i = 0; i < tabelModel.getRowCount(); i++){
            item.add(tabelModel.getValueAt(i, 0).toString());
        }
        for(String i : item) {
            if(i.equals(nama)) {
                hasil = true;
            } 
        }
        return hasil;
    } 
    
    // fungsi ini untuk mengecek apakah tabel kosong?
    private boolean isEmpty() {
        return this.varTab.getModel().getRowCount()<=0;
    }
    
    // tombol delete dan save akan disable jika tabel nya kosong
    private void cekBarang() {
        if(isEmpty()) {
            this.varSave.setEnabled(false);
            this.varDell.setEnabled(false);
        } else {
            this.varSave.setEnabled(true);
            this.varDell.setEnabled(true);
        }
    }
    
    //kode ini membuat transaksi baru setelah melakukan transaksi sebelumnya
    private void transaksiBaru() {
        this.varItem.setText("");
        this.varCode.setText("");
        this.varNew.setEnabled(true);
        this.varSave.setEnabled(false);
        this.varCancel.setEnabled(false);
        this.varAdd.setEnabled(false);
        this.varDell.setEnabled(false);
        this.varItem.setEnabled(false);
        this.varMenu.setEnabled(false);
        this.tabelModel.setRowCount(0);
        this.barang.clear();
    }


    /**
     * This method is called from within the constructor to initialize the Form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varNew = new javax.swing.JButton();
        varAdd = new javax.swing.JButton();
        varDell = new javax.swing.JButton();
        varCancel = new javax.swing.JButton();
        varSave = new javax.swing.JButton();
        code = new javax.swing.JLabel();
        items = new javax.swing.JLabel();
        varCode = new javax.swing.JTextField();
        varItem = new javax.swing.JTextField();
        varMenu = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        varTab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        varNew.setText("New");
        varNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNewActionPerformed(evt);
            }
        });

        varAdd.setText("Add");
        varAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varAddActionPerformed(evt);
            }
        });

        varDell.setText("Remove");
        varDell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varDellActionPerformed(evt);
            }
        });

        varCancel.setText("Cancel");
        varCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCancelActionPerformed(evt);
            }
        });

        varSave.setText("Save");
        varSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varSaveActionPerformed(evt);
            }
        });

        code.setText("Code");

        items.setText("Items");

        varCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCodeActionPerformed(evt);
            }
        });

        varMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Gula", "Susu" }));

        varTab.setModel(this.tabelModel);
        jScrollPane1.setViewportView(varTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(code))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(varItem, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addComponent(varCode))
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(varNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varDell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(varSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNew)
                    .addComponent(code)
                    .addComponent(varCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(varMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(varItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(varAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varDell)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCancel)
                    .addComponent(varSave))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNewActionPerformed
         this.varItem.setText("1");
        this.varNew.setEnabled(false);
        this.varCancel.setEnabled(true);
        this.varAdd.setEnabled(true);
        this.varItem.setEnabled(true);
        this.varMenu.setEnabled(true);
        this.varCode.setText(this.setKode());
    }//GEN-LAST:event_varNewActionPerformed

    private void varDellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varDellActionPerformed
        if(varTab.getSelectedRow()<0){
            String string = "Ingin menghapus yang mana? ";
            JOptionPane.showMessageDialog(this, string, "Informasi ", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int hitung = varTab.getSelectedRows().length;
                for(int i = 0; i < hitung; i++){
                    tabelModel.removeRow(varTab.getSelectedRow());
                }
        }
    }//GEN-LAST:event_varDellActionPerformed
 
    private void varCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCodeActionPerformed

    private void varCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCancelActionPerformed
        transaksiBaru();
        this.kurangId();
    }//GEN-LAST:event_varCancelActionPerformed

    private void varAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varAddActionPerformed
        String nama = this.varMenu.getSelectedItem().toString();
        int jumlah = new Integer(this.varItem.getText());
        
        if(isDuplicate(nama)){
            updateJumlah(nama, jumlah);
        } else {
            tabelModel.addRow(addItem(nama, jumlah));
        }
        this.cekBarang();
    }//GEN-LAST:event_varAddActionPerformed

    private void varSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varSaveActionPerformed
        try {
            for (int i = 0; i < tabelModel.getRowCount(); i++) {                   // loop each rows of the table then;
                String nama = tabelModel.getValueAt(i, 0).toString();              // store the name and the qty into variables then;
                float harga = new Float(tabelModel.getValueAt(i, 1).toString());   //
                int jumlah = new Integer(tabelModel.getValueAt(i, 2).toString());     //                
                this.barang.add(new Item(nama, harga, jumlah));                      //
            }
            Transaksi transaksi = new Transaksi(this.kode, this.barang); // instantiate Transact class with the current code and previously ommited cart
            StringBuilder string = new StringBuilder(); // Stringbuilder to handle the transaction output
            string.append(transaksi.detail()); // append transaction output
            JOptionPane.showMessageDialog(this, string, "Detail Transaksi", JOptionPane.INFORMATION_MESSAGE); // call the dialog with the stringbuilder's string
            transaksiBaru(); // start a new transaction after;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_varSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the Form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel code;
    private javax.swing.JLabel items;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton varAdd;
    private javax.swing.JButton varCancel;
    private javax.swing.JTextField varCode;
    private javax.swing.JButton varDell;
    private javax.swing.JTextField varItem;
    private javax.swing.JComboBox<String> varMenu;
    private javax.swing.JButton varNew;
    private javax.swing.JButton varSave;
    private javax.swing.JTable varTab;
    // End of variables declaration//GEN-END:variables
}
